
CUDA_VISIBLE_DEVICES=1 python3 ./federated_uncertainty_scripts/main_federated_ensembles.py \
    --n_models 50 \
    --n_clients 5 \
    --ensemble_size 5 \
    --lambda_disagreement 0.1 \
    --lambda_antireg 0.01 \
    --fraction 0.5 \
    --n_epochs 85 \
    --batch_size 256 \
    --lr 1e-4 \
    --spoiler_noise 5e-5 \
    --noise_type "noize_weights" \
    --market_lr 5e-3 \
    --market_epochs 2 \
    --model_min_classes 80 \
    --model_max_classes 90 \
    --client_min_classes 20 \
    --client_max_classes 50 \
    --save_dir "./data/saved_models/cifar100/test_run3" \
    --dataset "cifar100" \
    --seed 0